// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnxseePrcf7hN0_qoGdjGnd5_wi1dH9Z0',
    appId: '1:29503502694:web:0f9026e1422309897970a7',
    messagingSenderId: '29503502694',
    projectId: 'final-project-5b6ae',
    authDomain: 'final-project-5b6ae.firebaseapp.com',
    storageBucket: 'final-project-5b6ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjhPBe4kaND5f6e_p-EbAq5wSYWSNDHD4',
    appId: '1:29503502694:android:6ca2376c0b665f507970a7',
    messagingSenderId: '29503502694',
    projectId: 'final-project-5b6ae',
    storageBucket: 'final-project-5b6ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmuJ-ygJJT9nwycs2zAtuTZ562gcFTwbs',
    appId: '1:29503502694:ios:a2400df8e677ca1f7970a7',
    messagingSenderId: '29503502694',
    projectId: 'final-project-5b6ae',
    storageBucket: 'final-project-5b6ae.appspot.com',
    iosBundleId: 'com.example.frontendTambakku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmuJ-ygJJT9nwycs2zAtuTZ562gcFTwbs',
    appId: '1:29503502694:ios:a2400df8e677ca1f7970a7',
    messagingSenderId: '29503502694',
    projectId: 'final-project-5b6ae',
    storageBucket: 'final-project-5b6ae.appspot.com',
    iosBundleId: 'com.example.frontendTambakku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnxseePrcf7hN0_qoGdjGnd5_wi1dH9Z0',
    appId: '1:29503502694:web:6df5bf01ba8926e47970a7',
    messagingSenderId: '29503502694',
    projectId: 'final-project-5b6ae',
    authDomain: 'final-project-5b6ae.firebaseapp.com',
    storageBucket: 'final-project-5b6ae.appspot.com',
  );
}
